### ISSUE TITLE
PluginError.xml - Plugin doesn't start.

### ISSUE THREAD

**Issue by StefCoders** [EnderIce2/SDR-RPC#13]
I have reinstalled SDRSharp, just the newest version. And installed the plugin for the first time.

```
*** Plugin Load Error - 2024-01-23 20:42:01.285
DLL          'Plugins\System.Drawing.Common.dll'
Message      '0x80131621'
Stack Trace
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyBinder, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at SDRSharp.MainForm.LoadPluginTree(String directory, Dictionary`2 pluginTypes, List`1 orderedPluginKeys)

*** Plugin Load Error - 2024-01-23 20:42:01.299
Config Key   'EnderIce2.SDRSharpPlugin.MainPlugin,Plugins\SDR-RPC.dll'
Type         'EnderIce2.SDRSharpPlugin.MainPlugin, SDR-RPC, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'
Message      'Exception has been thrown by the target of an invocation.'
Stack Trace
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at SDRSharp.MainForm.InitializeSharpPlugins()


```

**Comment by EnderIce2** [comment]
Try removing `System.Drawing.Common.dll` and tell me if it works

**Comment by StefCoders** [comment]
```
*** Plugin Load Error - 2024-01-30 21:16:41.214
Config Key   'EnderIce2.SDRSharpPlugin.MainPlugin,Plugins\SDR-RPC.dll'
Type         'EnderIce2.SDRSharpPlugin.MainPlugin, SDR-RPC, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'
Message      'Exception has been thrown by the target of an invocation.'
Stack Trace
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at SDRSharp.MainForm.InitializeSharpPlugins()
```
