### ISSUE TITLE
load error with SDR# 1.0.0.1811

### ISSUE THREAD

**Issue by serge-golovanow** [EnderIce2/SDR-RPC#2]
Hello there,
When trying to use this plugin with SDR# rev 1811 :

```
*** Plugin Load Error - 2021-05-10 10:06:53.488
Config Key   'Discord RPC'
Type         'EnderIce2.SDRSharpPlugin.MainPlugin, SDR-RPC, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
Message      'Could not load file or assembly 'SDRSharpMerged, Version=1.0.0.1765, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable.'
Stack Trace
   at EnderIce2.SDRSharpPlugin.MainPlugin.Initialize(ISharpControl control)
   at SDRSharp.MainForm.InitializeSharpPlugins()
```

**Comment by EnderIce2** [comment]
It should be fixed now
https://github.com/EnderIce2/SDR-RPC/releases/tag/v1.0.0.1
